/**
 * prisma/seed.ts
 *
 * Reads etl/output/seed.json (generated by the Python ETL) and inserts all
 * records in FK-dependency order.
 *
 * Run with:     pnpm prisma db seed
 * Reset + seed: pnpm prisma migrate reset
 *
 * Design:
 *   1. validateSeed() checks all FK references in memory — fails fast with
 *      actionable errors before touching the DB.
 *   2. Ref tables are inserted in a single transaction (atomic, all-or-nothing).
 *   3. Universities, agreements, contacts, and observations are inserted in
 *      chunks without skipDuplicates — any failure surfaces immediately.
 *   4. IDs for FK guards are derived from the validated in-memory data,
 *      not from post-insert DB queries.
 */

import { prisma } from '../src/lib/prisma';
import {
  ContactConcernType,
  ContactValueType,
  ObservationOrigin,
  ObservationLevel,
} from '../src/generated/prisma/enums';
import * as fs from 'fs';
import * as path from 'path';

// ── Seed JSON types ───────────────────────────────────────────────────────────

interface RefRow {
  id: number;
  name: string;
}
interface RefValueRow {
  id: number;
  value: string;
  color: string | null;
}
interface RefBenefRow {
  id: number;
  cve: string;
  name: string;
}

interface UniversityRow {
  id: string;
  slug: string;
  name: string;
  start: string | null;
  expires: string | null;
  isCatholic: boolean;
  pagina_web: string | null;
  pagina_web_url: string | null;
  ciudad: string | null;
  direccion: string | null;
  regionId: number;
  countryId: number;
  institutionTypeId: number;
  campusId: number;
  utilizationId: number;
}

interface ContactRow {
  id: string;
  universityId: string;
  concernType: string;
  valueType: string;
  value: string;
}

interface AgreementRow {
  id: string;
  universityId: string;
  typeId: number;
  statusId: number;
  spots: number | null;
  link_convenio: string | null;
  attrIds: number[];
  beneficiaryIds: number[];
}

interface ObservationRow {
  text: string;
  origin: string;
  level: string;
  source: string | null;
  universityId: string | null;
  agreementId: string | null;
}

interface SeedData {
  ref_regions: RefRow[];
  ref_countries: RefRow[];
  ref_institution_types: RefRow[];
  ref_agreement_types: RefRow[];
  ref_campuses: RefRow[];
  ref_attrs: RefRow[];
  ref_statuses: RefValueRow[];
  ref_utilizations: RefValueRow[];
  ref_beneficiaries: RefBenefRow[];
  universities: UniversityRow[];
  contacts: ContactRow[];
  agreements: AgreementRow[];
  observations: ObservationRow[];
}

// ── Load ──────────────────────────────────────────────────────────────────────

const seedPath = path.resolve(__dirname, '../etl/output/seed.json');
const seed = JSON.parse(fs.readFileSync(seedPath, 'utf-8')) as SeedData;

// ── Helpers ───────────────────────────────────────────────────────────────────

function parseDate(value: string | null, fallback: Date): Date {
  if (!value) return fallback;
  const d = new Date(value);
  return isNaN(d.getTime()) ? fallback : d;
}

const EPOCH = new Date('1900-01-01');

function chunks<T>(arr: T[], size: number): T[][] {
  const out: T[][] = [];
  for (let i = 0; i < arr.length; i += size) out.push(arr.slice(i, i + size));
  return out;
}

// ── Validation ────────────────────────────────────────────────────────────────

/**
 * Validate all FK references in memory before touching the DB.
 * Exits with a non-zero code and actionable error messages if anything
 * is wrong — fix the Python ETL and regenerate seed.json.
 */
function validateSeed(data: SeedData): void {
  const errors: string[] = [];

  // Build id sets from each ref table
  const campusIds = new Set(data.ref_campuses.map((r) => r.id));
  const regionIds = new Set(data.ref_regions.map((r) => r.id));
  const countryIds = new Set(data.ref_countries.map((r) => r.id));
  const giroIds = new Set(data.ref_institution_types.map((r) => r.id));
  const utilIds = new Set(data.ref_utilizations.map((r) => r.id));
  const agreementTypeIds = new Set(data.ref_agreement_types.map((r) => r.id));
  const statusIds = new Set(data.ref_statuses.map((r) => r.id));
  const attrIds = new Set(data.ref_attrs.map((r) => r.id));
  const beneficiaryIds = new Set(data.ref_beneficiaries.map((r) => r.id));
  const universityIds = new Set(data.universities.map((u) => u.id));
  const agreementIds = new Set(data.agreements.map((a) => a.id));

  const usedSlugs = new Set<string>();

  // Universities → ref tables
  for (const u of data.universities) {
    // 2. Collision Check: If the slug is already in the set, it's a duplicate
    if (usedSlugs.has(u.slug)) {
      errors.push(
        `University "${u.name}": duplicate slug "${u.slug}" detected`
      );
    } else {
      // 3. If not a duplicate, add it so future iterations can catch it
      usedSlugs.add(u.slug);
    }

    if (!campusIds.has(u.campusId))
      errors.push(
        `University "${u.name}": campusId ${u.campusId} not in ref_campuses`
      );
    if (!regionIds.has(u.regionId))
      errors.push(
        `University "${u.name}": regionId ${u.regionId} not in ref_regions`
      );
    if (!countryIds.has(u.countryId))
      errors.push(
        `University "${u.name}": countryId ${u.countryId} not in ref_countries`
      );
    if (!giroIds.has(u.institutionTypeId))
      errors.push(
        `University "${u.name}": institutionTypeId ${u.institutionTypeId} not in ref_institution_types`
      );
    if (!utilIds.has(u.utilizationId))
      errors.push(
        `University "${u.name}": utilizationId ${u.utilizationId} not in ref_utilizations`
      );
  }

  // Agreements → universities + ref tables
  for (const a of data.agreements) {
    if (!universityIds.has(a.universityId))
      errors.push(
        `Agreement ${a.id}: universityId ${a.universityId} not in universities`
      );
    if (!agreementTypeIds.has(a.typeId))
      errors.push(
        `Agreement ${a.id}: typeId ${a.typeId} not in ref_agreement_types`
      );
    if (!statusIds.has(a.statusId))
      errors.push(
        `Agreement ${a.id}: statusId ${a.statusId} not in ref_statuses`
      );
    for (const attrId of a.attrIds) {
      if (!attrIds.has(attrId))
        errors.push(`Agreement ${a.id}: attrId ${attrId} not in ref_attrs`);
    }
    for (const benefId of a.beneficiaryIds) {
      if (!beneficiaryIds.has(benefId))
        errors.push(
          `Agreement ${a.id}: beneficiaryId ${benefId} not in ref_beneficiaries`
        );
    }
  }

  // Contacts → universities
  for (const c of data.contacts) {
    if (!universityIds.has(c.universityId))
      errors.push(
        `Contact "${c.value}": universityId ${c.universityId} not in universities`
      );
  }

  // Observations → universities or agreements (nullable — only validate when set)
  for (const o of data.observations) {
    if (o.universityId && !universityIds.has(o.universityId))
      errors.push(
        `Observation "${o.text.slice(0, 40)}…": universityId ${o.universityId} not in universities`
      );
    if (o.agreementId && !agreementIds.has(o.agreementId))
      errors.push(
        `Observation "${o.text.slice(0, 40)}…": agreementId ${o.agreementId} not in agreements`
      );
  }

  if (errors.length > 0) {
    console.error(
      `\n❌ seed.json validation failed — ${errors.length} FK error(s):\n`
    );
    // Show first 20 to avoid wall of text
    errors.slice(0, 20).forEach((e) => console.error(`   • ${e}`));
    if (errors.length > 20)
      console.error(`   … and ${errors.length - 20} more`);
    console.error(
      '\n→ Fix the Python ETL and regenerate seed.json before seeding.\n'
    );
    process.exit(1);
  }

  console.log(
    `✓ Validation passed — ${data.universities.length} universities, ` +
      `${data.agreements.length} agreements, ${data.contacts.length} contacts, ` +
      `${data.observations.length} observations\n`
  );
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function main() {
  console.log('🌱 Seeding from ETL output…\n');

  // Validate all FK references before touching the DB.
  // Exits with a descriptive error if anything is wrong.
  validateSeed(seed);

  // // Derive id sets from validated in-memory data — no post-insert DB queries.
  // const universityIds = new Set(seed.universities.map((u) => u.id));
  // const agreementIds = new Set(seed.agreements.map((a) => a.id));

  // ── 1. Reference tables (single transaction) ──────────────────────────────

  console.log('→ reference tables');
  await prisma.$transaction([
    prisma.refRegion.createMany({
      data: seed.ref_regions.map((r) => ({ id: r.id, name: r.name })),
      skipDuplicates: true,
    }),
    prisma.refCountry.createMany({
      data: seed.ref_countries.map((r) => ({ id: r.id, name: r.name })),
      skipDuplicates: true,
    }),
    prisma.refInstitutionType.createMany({
      data: seed.ref_institution_types.map((r) => ({ id: r.id, name: r.name })),
      skipDuplicates: true,
    }),
    prisma.refCampus.createMany({
      data: seed.ref_campuses.map((r) => ({ id: r.id, name: r.name })),
      skipDuplicates: true,
    }),
    prisma.refAgreementType.createMany({
      data: seed.ref_agreement_types.map((r) => ({ id: r.id, name: r.name })),
      skipDuplicates: true,
    }),
    prisma.refAttr.createMany({
      data: seed.ref_attrs.map((r) => ({ id: r.id, name: r.name })),
      skipDuplicates: true,
    }),
    prisma.refStatus.createMany({
      data: seed.ref_statuses.map((r) => ({
        id: r.id,
        value: r.value,
        color: r.color,
      })),
      skipDuplicates: true,
    }),
    prisma.refUtilization.createMany({
      data: seed.ref_utilizations.map((r) => ({
        id: r.id,
        value: r.value,
        color: r.color,
      })),
      skipDuplicates: true,
    }),
    prisma.refBeneficiary.createMany({
      data: seed.ref_beneficiaries.map((r) => ({
        id: r.id,
        cve: r.cve,
        name: r.name,
      })),
      skipDuplicates: true,
    }),
  ]);
  console.log('  ✓ all reference tables committed\n');

  // ── 2. Universities ───────────────────────────────────────────────────────

  console.log(`→ universities (${seed.universities.length})`);
  for (const chunk of chunks(seed.universities, 50)) {
    await prisma.university.createMany({
      data: chunk.map((u) => ({
        id: u.id,
        slug: u.slug,
        name: u.name,
        start: parseDate(u.start, EPOCH),
        expires: u.expires ? new Date(u.expires) : null,
        isCatholic: u.isCatholic,
        pagina_web: u.pagina_web_url ?? u.pagina_web,
        city: u.ciudad,
        address: u.direccion,
        regionId: u.regionId,
        countryId: u.countryId,
        institutionTypeId: u.institutionTypeId,
        campusId: u.campusId,
        utilizationId: u.utilizationId,
      })),
    });
  }
  console.log(`  ✓ ${seed.universities.length} inserted\n`);

  // ── 3. Contacts ───────────────────────────────────────────────────────────

  console.log(`→ contacts (${seed.contacts.length})`);
  await prisma.contact.createMany({
    data: seed.contacts.map((c) => ({
      id: c.id,
      universityId: c.universityId,
      concernType: c.concernType as ContactConcernType,
      valueType: c.valueType as ContactValueType,
      value: c.value,
      name: null,
    })),
  });
  console.log(`  ✓ ${seed.contacts.length} inserted\n`);

  // ── 4. Agreements ─────────────────────────────────────────────────────────

  console.log(`→ agreements (${seed.agreements.length})`);
  for (const chunk of chunks(seed.agreements, 50)) {
    await prisma.agreement.createMany({
      data: chunk.map((a) => ({
        id: a.id,
        universityId: a.universityId,
        typeId: a.typeId,
        statusId: a.statusId,
        spots: a.spots,
        link_convenio: a.link_convenio,
      })),
    });
  }
  console.log(`  ✓ ${seed.agreements.length} inserted\n`);

  // ── 5. Agreement junctions ────────────────────────────────────────────────

  console.log('→ agreement junctions');
  const attrRows = seed.agreements.flatMap((a) =>
    a.attrIds.map((attrId) => ({ agreementId: a.id, attrId }))
  );
  const benefRows = seed.agreements.flatMap((a) =>
    a.beneficiaryIds.map((beneficiaryId) => ({
      agreementId: a.id,
      beneficiaryId,
    }))
  );

  await prisma.$transaction([
    ...(attrRows.length
      ? [prisma.agreementAttr.createMany({ data: attrRows })]
      : []),
    ...(benefRows.length
      ? [prisma.agreementBeneficiary.createMany({ data: benefRows })]
      : []),
  ]);
  console.log(
    `  ✓ ${attrRows.length} attrs, ${benefRows.length} beneficiaries\n`
  );

  // ── 6. Observations ───────────────────────────────────────────────────────

  console.log(`→ observations (${seed.observations.length})`);
  for (const chunk of chunks(seed.observations, 100)) {
    await prisma.observation.createMany({
      data: chunk.map((o) => ({
        text: o.text,
        origin: o.origin as ObservationOrigin,
        level: o.level as ObservationLevel,
        source: o.source,
        universityId: o.universityId,
        agreementId: o.agreementId,
      })),
    });
  }
  console.log(`  ✓ ${seed.observations.length} inserted\n`);

  // ── Fix sequences ─────────────────────────────────────────────────────────
  // The ETL inserted rows with explicit IDs, which leaves Postgres sequences
  // pointing at 1 even though higher IDs exist. Reset each sequence to
  // MAX(id) + 1 so subsequent INSERTs use the correct next value.

  console.log('→ fixing sequences');
  const refTables: [string, string][] = [
    ['ref_region', 'id'],
    ['ref_pais', 'id'],
    ['ref_giro', 'id'],
    ['ref_campus', 'id'],
    ['ref_agreement_type', 'id'],
    ['ref_attr', 'id'],
    ['ref_status', 'id'],
    ['ref_utilization', 'id'],
    ['ref_beneficiary', 'id'],
  ];
  for (const [table, col] of refTables) {
    await prisma.$executeRawUnsafe(
      `SELECT setval(pg_get_serial_sequence('${table}', '${col}'), (SELECT MAX(${col}) FROM "${table}") + 1, false)`
    );
  }
  console.log('  ✓ sequences reset\n');

  // ── Summary ───────────────────────────────────────────────────────────────

  const [uniCount, agrCount, conCount, obsCount] = await Promise.all([
    prisma.university.count(),
    prisma.agreement.count(),
    prisma.contact.count(),
    prisma.observation.count(),
  ]);
  console.log('✅ Done');
  console.log(`   Universities : ${uniCount}`);
  console.log(`   Agreements   : ${agrCount}`);
  console.log(`   Contacts     : ${conCount}`);
  console.log(`   Observations : ${obsCount}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
